<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.29">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.29" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StoreManagementSystem.Application\StoreManagementSystem.Application.csproj" />
    <ProjectReference Include="..\StoreManagementSystem.Domain\StoreManagementSystem.Domain.csproj" />
    <ProjectReference Include="..\StoreManagementSystem.Shared\StoreManagementSystem.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
    <Folder Include="Migrations\" />
    <Folder Include="Seed\" />
  </ItemGroup>

</Project>
